nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs

npmScopes:
  rodogir:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${GITHUB_TOKEN}
